# Generated by Django 2.0.3 on 2018-03-20 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbqplanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbqevent',
            options={'ordering': ['-date']},
        ),
    ]
