FROM python:3
ENV PYTHONUNBUFFERED 1

RUN mkdir /code
WORKDIR /code

RUN pip install pip-tools
ADD requirements.in /code/
RUN pip-compile --upgrade requirements.in
RUN pip-sync requirements.txt

ADD . /code/
