version: '3'

services:
  db:
    image: postgres
  web:
    build: 
      context: .
      dockerfile: Dockerfile.django
    command: bash ./start.sh
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db