FROM python:3
ENV PYTHONUNBUFFERED 1

RUN mkdir /code
WORKDIR /code

RUN pip install pip-tools
ADD requirements.in /code/
RUN pip-compile --upgrade requirements.in
RUN pip-sync requirements.txt

ADD . /code/

RUN python manage.py makemigrations
RUN python manage.py migrate

RUN echo "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@example.com', 'pass')" | python manage.py shell

RUN python manage.py loaddata fixtures/products.json
