# Generated by Django 2.0.3 on 2018-03-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbqproducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbqproduct',
            name='type_name',
            field=models.CharField(default='Meat', max_length=20),
        ),
    ]
